server:
  port: 8081   #端口号
  tomcat:
    initial-size: 64 #初始化内存
    min-free-size: 64 #最小内存
    max-size: 128     #最小内存
    max-threads: 100
    min-spare-threads: 10
  executor:
    defaultCoreSize: 2 #默认线程池
    logicCoreSize: 10 #逻辑线程池

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: mysql-dev
  web:
    resources:
      static-locations: classpath:/public/

  servlet:
    multipart: # 文件上传配置
      enabled: false
  task:
    scheduling: # 定时任务线程池配置
      pool:
        size: 2
